"""empty message

Revision ID: 5db37ad86a15
Revises: c211e8988bd7
Create Date: 2022-08-08 23:14:35.313005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5db37ad86a15'
down_revision = 'c211e8988bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscription_icons_subscription_id', table_name='subscription_icons')
    op.drop_table('subscription_icons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_icons',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('subscription_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name='subscription_icons_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_subscription_icons_subscription_id', 'subscription_icons', ['subscription_id'], unique=False)
    # ### end Alembic commands ###
