"""empty message

Revision ID: 8e7c42fdc259
Revises: 0281d61d9bde
Create Date: 2022-08-08 20:57:47.526867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e7c42fdc259'
down_revision = '0281d61d9bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'next_bill',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)
    op.alter_column('subscriptions', 'next_bill',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
