"""empty message

Revision ID: b935d4e84104
Revises: c5d8ba4a810f
Create Date: 2022-08-08 23:11:57.985847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b935d4e84104'
down_revision = 'c5d8ba4a810f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_icons', 'subscription_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)
    op.drop_index('ix_subscription_icons_subscription_id', table_name='subscription_icons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subscription_icons_subscription_id', 'subscription_icons', ['subscription_id'], unique=False)
    op.alter_column('subscription_icons', 'subscription_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)
    # ### end Alembic commands ###
