"""empty message

Revision ID: c211e8988bd7
Revises: b935d4e84104
Create Date: 2022-08-08 23:12:43.943409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c211e8988bd7'
down_revision = 'b935d4e84104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_icons', 'subscription_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_icons', 'subscription_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)
    # ### end Alembic commands ###
