"""empty message

Revision ID: c5d8ba4a810f
Revises: ea38047d1673
Create Date: 2022-08-08 23:07:36.252177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d8ba4a810f'
down_revision = 'ea38047d1673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscription_icons_ibfk_1', 'subscription_icons', type_='foreignkey')
    op.create_foreign_key(None, 'subscription_icons', 'subscriptions', ['subscription_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_icons', type_='foreignkey')
    op.create_foreign_key('subscription_icons_ibfk_1', 'subscription_icons', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
