"""empty message

Revision ID: ea38047d1673
Revises: c1152fe1a905
Create Date: 2022-08-08 23:06:44.963651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea38047d1673'
down_revision = 'c1152fe1a905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscription_icons_ibfk_1', 'subscription_icons', type_='foreignkey')
    op.create_foreign_key(None, 'subscription_icons', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_icons', type_='foreignkey')
    op.create_foreign_key('subscription_icons_ibfk_1', 'subscription_icons', 'subscriptions', ['subscription_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
