"""empty message

Revision ID: eaf5ad48754a
Revises: 532e8aeca5d5
Create Date: 2022-08-08 23:17:06.747637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eaf5ad48754a'
down_revision = '532e8aeca5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admins',
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_admins_user_id'), 'admins', ['user_id'], unique=True)
    op.create_table('clients',
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=True)
    op.create_table('role_users',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('role_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_users_role_id'), 'role_users', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_users_user_id'), 'role_users', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('already_seen', sa.Boolean(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'client_id')
    )
    op.create_index(op.f('ix_notifications_client_id'), 'notifications', ['client_id'], unique=False)
    op.create_table('subscription_templates',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('admin_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('background', sa.Enum('#FFF001', '#FEC10E', '#F7921E', '#EF6421', '#EB1C24', '#932490', '#000000', '#642C91', '#0070BA', '#01ABEF', '#01A99C', '#01A451', '#8BC53D', '#C4C4C4'), nullable=False),
    sa.Column('category', sa.Enum('music', 'entertainment', 'utilities', 'food_and_beverages', 'health_and_wellbeing', 'productivity', 'banking', 'transport', 'education', 'insurance'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'admin_id')
    )
    op.create_index(op.f('ix_subscription_templates_admin_id'), 'subscription_templates', ['admin_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('next_bill', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('billing_cycle', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('remind', sa.Boolean(), nullable=True),
    sa.Column('is_continuous', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('background', sa.Enum('#FFF001', '#FEC10E', '#F7921E', '#EF6421', '#EB1C24', '#932490', '#000000', '#642C91', '#0070BA', '#01ABEF', '#01A99C', '#01A451', '#8BC53D', '#C4C4C4'), nullable=True),
    sa.Column('category', sa.Enum('music', 'entertainment', 'utilities', 'food_and_beverages', 'health_and_wellbeing', 'productivity', 'banking', 'transport', 'education', 'insurance'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'client_id')
    )
    op.create_index(op.f('ix_subscriptions_client_id'), 'subscriptions', ['client_id'], unique=False)
    op.create_table('subscription_template_icons',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('subscription_template_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('url', sa.String(length=400), nullable=False),
    sa.Column('key', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_template_id'], ['subscription_templates.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_template_icons_subscription_template_id'), 'subscription_template_icons', ['subscription_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_template_icons_subscription_template_id'), table_name='subscription_template_icons')
    op.drop_table('subscription_template_icons')
    op.drop_index(op.f('ix_subscriptions_client_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_subscription_templates_admin_id'), table_name='subscription_templates')
    op.drop_table('subscription_templates')
    op.drop_index(op.f('ix_notifications_client_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_role_users_user_id'), table_name='role_users')
    op.drop_index(op.f('ix_role_users_role_id'), table_name='role_users')
    op.drop_table('role_users')
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_admins_user_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
